#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ProductsDBMySQL.Data;

namespace ProductsDBMySQL.Data	
{
	public partial class Product
	{
		private int _products_ID;
		public virtual int Products_ID
		{
			get
			{
				return this._products_ID;
			}
			set
			{
				this._products_ID = value;
			}
		}
		
		private string _product_Name;
		public virtual string Product_Name
		{
			get
			{
				return this._product_Name;
			}
			set
			{
				this._product_Name = value;
			}
		}
		
		private long _basePrice;
		public virtual long BasePrice
		{
			get
			{
				return this._basePrice;
			}
			set
			{
				this._basePrice = value;
			}
		}
		
		private int _vendors_Vendor_ID;
		public virtual int Vendors_Vendor_ID
		{
			get
			{
				return this._vendors_Vendor_ID;
			}
			set
			{
				this._vendors_Vendor_ID = value;
			}
		}
		
		private int _measures_Measure_ID;
		public virtual int Measures_Measure_ID
		{
			get
			{
				return this._measures_Measure_ID;
			}
			set
			{
				this._measures_Measure_ID = value;
			}
		}
		
		private Measure _measure;
		public virtual Measure Measure
		{
			get
			{
				return this._measure;
			}
			set
			{
				this._measure = value;
			}
		}
		
		private Vendor _vendor;
		public virtual Vendor Vendor
		{
			get
			{
				return this._vendor;
			}
			set
			{
				this._vendor = value;
			}
		}
		
	}
}
#pragma warning restore 1591
