//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpessartiteTwitter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.Comments = new HashSet<Comment>();
            this.Tweets = new HashSet<Tweet>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }

        [ScaffoldColumn(false)]
        public string Id { get; set; }

        [ScaffoldColumn(false)]
        public string UserName { get; set; }

        [MinLength(2), MaxLength(30)]
        public string FirstName { get; set; }

        [MinLength(4), MaxLength(30)]
        public string LastName { get; set; }

        [Required, Range(4, 100)]
        public Nullable<int> Age { get; set; }
        public byte[] Picture { get; set; }
        public string MobilePhone { get; set; }
        public string AboutMe { get; set; }
        public string WebSite { get; set; }
        public string Skype { get; set; }
        public string Facebook { get; set; }

        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual AspNetUserManagement AspNetUserManagement { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Tweet> Tweets { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
