//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpessartiteTwitter.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Tweet
    {
        public Tweet()
        {
            this.Comments = new HashSet<Comment>();
        }

        [ScaffoldColumn(false)]
        public int TweetId { get; set; }

        [Required, MinLength(6), MaxLength(2000)]
        public string TweetText { get; set; }

        [Required, Range(typeof(DateTime), "1/1/2013", "1/1/2015"), DisplayFormat(ApplyFormatInEditMode = true,
            DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime DatePosted { get; set; }
        public byte[] Image { get; set; }

        [ScaffoldColumn(false)]
        public string UserId { get; set; }

        [Required, MinLength(6), MaxLength(200)]
        public string TweetTitle { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
